{% set name = "numbagg" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numbagg-{{ version }}.tar.gz
  sha256: ea0dab69a1f4593d54f11fbab46e20c7f7f81ec0e96b48201341e84cb6caa921

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - numpy
    - numba

test:
  imports:
    - numbagg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/numbagg/numbagg
  summary: Fast N-dimensional aggregation functions with Numba
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
